DROP TABLE dbo.Comments
DROP TABLE dbo.Events
DROP TABLE dbo.Followings
DROP TABLE dbo.Genres
DROP TABLE dbo.Likes
DROP TABLE dbo.Playlists
DROP TABLE dbo.PlaylistSongs
DROP TABLE dbo.Songs
DROP TABLE dbo.Users