DROP TABLE dbo.AspNetRoles
DROP TABLE dbo.AspNetUserClaims
DROP TABLE dbo.AspNetUserLogins
DROP TABLE dbo.AspNetUserRoles
DROP TABLE dbo.AspNetUsers
DROP TABLE dbo.AspNetUserTokens
DROP TABLE dbo.Genres
DROP TABLE dbo.Likes
DROP TABLE dbo.Playlists
DROP TABLE dbo.PlaylistSongs
DROP TABLE dbo.Songs